---
- name: Resolve redirect early for Python < 2.7.9
  script: resolve-redirect.sh {{ ansible_python_version }} {{ go_download_location }}
  register: go_download_location_adjusted

- name: Download the Go tarball
  get_url: url={{ go_download_location_adjusted.stdout }}
           dest=/usr/local/src/{{ go_tarball }}
           sha256sum={{ go_tarball_checksum }}

- name: Register the current Go version (if any)
  command: /usr/local/go/bin/go version
  ignore_errors: yes
  register: go_version
  changed_when: false

# - name: Extract the Go tarball if Go is not yet installed or not the desired version
#   unarchive: src="/usr/local/src/{{ go_tarball }}"
#              dest="/usr/local"
#              remote_src=yes
#   when: go_version|failed or go_version.stdout != go_version_target

- name: Remove old Go version
  file:
    path: /usr/local/go
    state: absent
  when: go_version|failed or go_version.stdout != go_version_target

- name: Extract tarball
  command: "tar xzf /usr/local/src/{{ go_tarball }}"
  args:
    creates: "/usr/local/go"
    chdir: /usr/local/
    timeout: 4000
  when: go_version|failed or go_version.stdout != go_version_target

- name: Add the Go bin directory to the PATH environment variable for all users
  copy: src=go-bin.sh
        dest=/etc/profile.d

- name: Set GOPATH for all users
  template: src=go-path.sh
        dest=/etc/profile.d

- name: Include configuration to Go Get private repos
  command: 'git config --global url."git@github.com:".insteadOf "https://github.com"'
  sudo: yes
  sudo_user: "{{ user }}"

- name: Include github key to known_hosts
  shell: "ssh-keyscan -t rsa github.com >> /home/{{ user }}/.ssh/known_hosts"
  sudo: yes
  sudo_user: "{{ user }}"

- name: Go Get/Update desired repos
  command: "/usr/local/go/bin/go get -u {{ item }}"
  environment:
    GOPATH: "{{ go_path }}"
  sudo: yes
  sudo_user: "{{ user }}"
  with_items: "{{ go_get | default([]) }}"
